airavata_mft/apps/workspace/urls.py
from . import views
from django.conf.urls import url

app_name='workspace'
urlpatterns = [
    url(r'^storage/$', views.storage,name="storages"),
    url(r'^transfers/$', views.transfers,name="resources"),
    url(r'^storage/filetransfer/$', views.filetransfer,name="file-transfer"),
    url(r'^storage/newunit/$', views.newunit,name="new-unit")
]

airavata_mft/urls.py
from django.contrib import admin
from django.urls import include
from django.conf.urls import url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^workspace/', include('airavata_mft.apps.workspace.urls'))
]

airavata_mft/apps/workspace/models.py
from django.db import models

# Create your models here.

airavata_mft/apps/workspace/views.py
from django.shortcuts import render
import json
# Create your views here.


def storage(request):
    # TODO: grpc calls to backend
    storage_json = [{"storageId": "ssh-storage1", "name": "Source 1","type": "SCP","owner": "Akhil", "lastModified":"01/15/2020"},
                    {"storageId": "ssh-storage2", "name": "Source 2","type": "SCP", "owner": "vivek","lastModified":"01/16/2020"},
                    {"storageId": "ssh-storage3", "name": "Destination 1","type": "S3","owner": "Dimuthu", "lastModified":"02/15/2020"},
                    {"storageId": "ssh-storage4", "name": "Destination 2","type": "SCP","owner": "suresh", "lastModified":"01/15/2019"}]

    return render(request, 'storage.html', {'bundle_name': 'storage',
                                            'data': json.dumps(storage_json),
                                            'title': 'Storage Unit'})


def transfers(request):
    resource_json = [{"transferId": "1", "Initialstorage": "Source 1", "Finalstorage": "Destination 1","Size":"10Mb","FileName":"image.jpeg","TransferDate": "01/15/2020"},
                     {"transferId": "2", "Initialstorage": "Source 2", "Finalstorage": "Destination 2", "Size":"1Mb","FileName":"abc.py","TransferDate": "02/15/2020"}]
    return render(request, 'transfers.html', {'bundle_name': 'transfers',
                                              'data': json.dumps(resource_json),
                                              'title':  'Transfers'})

def filetransfer(request):
    initial_storage_json = [{
  "file1": "image.jpeg",
  "file2": "file2.jpeg",
  "file3": "file3.jpeg",
  "dir1": {
    "file3": "image2.jpeg",
    "file4": "image4.jpeg",
    "dire2": {
      "file4": "file4.py",
      "file5": "file6.py"
    }
  }
}],
    final_storage_json = [{
  "file5": "image.jpeg",
  "file6": "file11.jpeg",
  "file7": "file12.jpeg",
  "dir8": {
    "file9": "image2.jpeg",
    "file10": "image4.jpeg",
    "dire9": {
      "file12": "file4.py",
      "file15": "file6.py"
    }
  }
}]
    return render(request,'filetransfer.html',{'bundle_name':'filetransfer',
                                                'initial_data':json.dumps(initial_storage_json),
                                                'final_data':json.dumps(final_storage_json),
                                                'title':'filetransfer'})


def newunit(request):
    
    return render(request,'newstorage.html',{'bundle_name':'newunit'})

airavata_mft/apps/workspace/templates/airavata_mft_workspace/storage.html
{% extends "base.html" %}
{% block app %}
    This is where list of storage unit goes
{% endblock app %}

airavata_mft/apps/workspace/templates/container-header.html
{% extends "base.html" %}

{% load static %}
{% load render_bundle from webpack_loader %}

{% block scripts %}
    {% render_bundle "chunk-vendors" config='WORKSPACE'%}
    {% render_bundle bundle_name config='WORKSPACE'%}
{% endblock scripts %}

{% block app %}
    
<div id={{ bundle_name }}></div>
{% endblock app %}

airavata_mft/apps/workspace/templates/filetransfer.html
{% extends "container-header.html" %}

{% block app %}
<div id={{ bundle_name }} data-initial-list="{{ initial_data }}"  data-final-list="{{ final_data }}"  data-title ="{{ title }}"></div> 
{% endblock app %}

airavata_mft/apps/workspace/templates/newstorage.html
{% extends "container-header.html" %}

{% block app %}
<div id={{ bundle_name }}></div>
{% endblock app %}

airavata_mft/apps/workspace/templates/storage.html
{% extends "container-header.html" %}

{% block app %}
    
<div id={{ bundle_name }} data-storage-list="{{ data }}" data-title ="{{ title }}"></div>
{% endblock app %}

airavata_mft/apps/workspace/templates/transfers.html
{% extends "container-header.html" %}

{% block app %}
    
<div id={{ bundle_name }} data-transfers-list="{{ data }}" data-title ="{{ title }}"></div>

{% endblock app %}

airavata_mft/templates/base.html
{% load static %}
{% load render_bundle from webpack_loader %}

<!DOCTYPE html>
<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	</head>
{% block scripts %}
{% endblock scripts %}
{% render_bundle 'chunk-vendors' config='DEFAULT'%}
{% render_bundle 'app' config='DEFAULT'%}

	<body>
		<nav class="navbar navbar-light header shadow-sm">
			<div class="container-fluid">
				<div class="col-2">
					<a class="navbar-brand" href = "{% url 'workspace:storages' %}">
						<div class="row">
							<div class="col-5">
								<img class="logo" src="{% static 'images/airavata-logo.png' %}">
								</div>
								<div>
									<div class="col-8">
										<div class="row apache">
											<span class="header-text apache-text">APACHE</span>
										</div>
										<div class="row airavata">
											<span class="header-text airavata-text">AIRAVATA</span>
										</div>
									</div>
								</div>
							</div>
						</a>
					</div>
					<div class="col-8 search-div">
						</div>
						<div class="col-2">
							<div class="row user-div">
								<i class="fa fa-user-circle fa-2x"></i>
								<div class="dropdown">
									<a class="btn dropdown-toggle header-drop-down" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Admin</a>
									<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
										<a class="dropdown-item" href="#">Logout</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</nav>
				<!-- side navigation bar (Needs to move to a vue template)-->
				<div class="container-fluid">
					<div class="row">
						<div class="col-2" style="padding-top: 1.5%">
							<nav class="nav flex-column">
								<a class="c-nav__item selected-nav" href= "{% url 'workspace:storages' %}">
									<i class="fa fa-database nav-icon"></i>Storage Units
								</a>
								<a class="c-nav__item" href="{% url 'workspace:resources' %}">
									<i class="fa fa-exchange nav-icon"></i> Transfers
                                </a>
							</nav>
						</div>
						<div class="col-10 main-app">
                {% block app %}
                {% endblock app %}
            </div>
					</div>
				</div>
			</body>
			<style>
     /* Side Navigation Bar */
    .selected-nav{
        margin-right: 0.5em;
        color: lightblue;
        padding: 1em;
        font-size: 1rem;
        display: block;
    }
    .c-nav__item {
        color: grey;
        padding: 1em;
        font-size: 1rem;
        display: block;
        background-color: white;
        padding-bottom: 0%;
    }
    .c-nav__item:hover{
        background-color: #d6d8db!important;
    }
    .nav-icon {
        padding-right: 10%;
        padding-left: 14%;
    }
    .c-nav__item:hover{
        color: #17a2b8;
        text-decoration: none;
        font-weight:bold;
    }
       /* Top Navigation */

    .header {
        background-color: white;
        padding-top: 2%;
    }
    .logo{
        height: 57px;
    }
    .header-text{
        color: grey;
    }
    .header-drop-down {
        color: black;
        background-color: white;
        border: white;
    }
    .apache {
        height: 0.7em;
    }
    .apache-text{
       font-size: smaller;
    }
    .airavata-text{
        font-size: larger;
    }
    
    /* Bootstrap 4 text input with search icon */

    .form-control {
        padding-left: 2.375rem;
        background-color: #DCDCDC;
        max-width: 58%;
    }

    .has-search .form-control-feedback {
        position: absolute;
        z-index: 2;
        display: block;
        width: 2.375rem;
        height: 2.375rem;
        line-height: 2.375rem;
        text-align: center;
        pointer-events: none;
        color: #aaa;
    }
    .search-div{
        padding-left: 0%;
    }
      /* main-app */
    .main-app{
        padding-top: 1.5%
    }
</style>